# Generated by Django 4.1.3 on 2022-12-16 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('place', models.CharField(max_length=50, verbose_name='旅行場所')),
                ('memory_image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='写真')),
                ('weather', models.CharField(max_length=20, verbose_name='天気')),
                ('feeling', models.CharField(max_length=2000, null=True, verbose_name='感想')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
        ),
        migrations.CreateModel(
            name='MemoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日時')),
                ('image', models.ImageField(upload_to='images', verbose_name='画像')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='memory.memory', verbose_name='メモリー')),
            ],
        ),
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='緯度')),
                ('lng', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='経度')),
                ('ken', models.CharField(blank=True, max_length=50, verbose_name='都道府県')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo', to='memory.memory', verbose_name='旅行場所')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='写真のパス')),
                ('birthplace', models.CharField(blank=True, max_length=20, verbose_name='出生地')),
                ('registerd_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='会員登録日時')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー名')),
            ],
        ),
    ]
